### ISSUE TITLE
eth_getTransactionReceipt rpc returns 0x contract address

### ISSUE THREAD

**Issue by zmcNotafraid** [nervosnetwork/godwoken-web3#360] opened 2022-05-27 02:36 UTC
Before I invoke `eth_getTransactionReceipt `RPC method, if it can't deploy a contract, the contract address returns "null" .But now it returns "0x".
Anything update?

Related issue:
- #363

**Comment by Kuzirashi** [comment] 2022-05-27 14:51
I have exactly the same problem: https://github.com/nervosnetwork/godwoken-web3/issues/363. I closed my issue as duplicate of yours because you were first who reported it. 👍

**Comment by Kuzirashi** [comment] 2022-05-30 09:26
Adding more context. This issue is blocking not only Gnosis Safe indexer, but also graph-node:
![image](https://user-images.githubusercontent.com/4950658/170961867-caeefc0e-fb51-4b2d-84ad-5329ac6a3e7d.png)

**Closed** 2022-06-02 00:29 UTC
Labels: bug, P-High
