### ISSUE TITLE
[v1.1] tx.gasprice always is 1

### ISSUE THREAD

**Issue by gpBlockchain** [nervosnetwork/godwoken-web3#377] opened 2022-06-02 08:47 UTC
#### env
rpcUrl:https://godwoken-betanet-v1.ckbapp.dev

#### code
```
pragma solidity ^0.8.4;

contract opcodeTxWithMsg{

    opcodeTxWithMsg ptw;

    event MsgTxEvent(uint256 idx,MsgData  msgData,TxData  txData);
    struct MsgData{
        bytes msgData;
        bytes4 msgSig;
        uint  msgValue;
        address msgSender;
    }

    struct TxData{
        uint txGasPrice;
        address txOrigin;
    }
    MsgData public msgData;
    TxData public txData;

    constructor () public payable {
        updateMsgAndTxData();
    }


    function getCurrentMsgDataAndTxData() public payable returns(MsgData memory,TxData memory){
        return (MsgData(msg.data,msg.sig,msg.value,msg.sender),TxData(tx.gasprice,tx.origin));
    }

    function updateMsgAndTxData() public payable {
        (msgData ,txData)= getCurrentMsgDataAndTxData();
        emit MsgTxEvent(1,msgData,txData);
    }

    function call_updateMsgAndTxData(address _addr) public payable{
        ptw = opcodeTxWithMsg(_addr);
        ptw.updateMsgAndTxData{value:msg.value}();
    }

}

```
#### step:
1. deploy opcodeTxWithMsg({gasPrice:111})
2. call txData 
3. invoke updateMsgAndTxData({gasPrice:111})
4. call txData
#### response
1. deploy success
2. call response txData.txGasPrice = 1
3. invoke success
4. call response txData.txGasPrice = 1

**Comment by keroro520** [comment] 2022-06-13 02:55
This issue can be reproduced by the below testcase:



AccessTxContext.sol:

```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.4;

contract AccessTxContext {
    uint public lastTxGasPrice;

    constructor () payable {
    }

    function getLastTxGasPrice() public view returns(uint) {
        return lastTxGasPrice;
    }

    function updateLastTxGasPrice() public payable {
        lastTxGasPrice = tx.gasprice;
    }
}
```



AccessTxContext.js:

```js
const { expect } = require("chai");
const { ethers, web3 } = require("hardhat");

describe("AccessTxContext", function () {
    it("AccessTxContext", async () => {
        const Storage = await ethers.getContractFactory("AccessTxContext");
        const contract = await Storage.deploy();
        await contract.deployed()

        console.log("TxGasPrice[1]: ", await contract.getLastTxGasPrice());

        await (await contract.updateLastTxGasPrice({gasPrice: 11111})).wait();
        console.log("TxGasPrice[2]: ", await contract.getLastTxGasPrice());
    })
})
```

**Comment by keroro520** [comment] 2022-06-13 02:55
The root cause is that `OP_GASPRICE` intends to access the tx.gasprice, but Polyjuice has hardcoded `tx gas price = 1`  before evmone execution so that `OP_GASPRICE` always gets `0x1`.

**Comment by magicalne** [comment] 2022-06-23 06:22
This will be fixed in polyjuice v1.3.

**Closed** 2022-07-06 03:06 UTC
Labels: polyjuice
